sudo: required
language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.5.1
before_install:
- gem install bundler -v 2.0.1
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry sudo apt-get update; sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb ; fi
script:
- plantuml -testdot
- make clean all publish deploy
