version: '{build}'

# https://help.appveyor.com/discussions/questions/1929-create-a-docker-machine-in-appveyor-build-nested-hypervisor-needed
image: Visual Studio 2017

build: off

test_script:
  - bitsadmin /transfer get https://raw.githubusercontent.com/CAMOBAP795/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
  - set PATH=c:\tools\ruby25\bin;%PATH% # make lookup ruby25 before preinstalled one
  - refreshenv
  - make -f Makefile.win clean all
  - exit /B %ERRORLEVEL%
  - echo "Test DONE"

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.*
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\images
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\reference-docs

artifacts:
  - path: metanorma_install.log
    name: install.log
  - path: install.bat
    name: install.bat
  - path: unece-cefact-recommendation-42.zip
    name: result.zip