:repo-name: unece-cefact-recommendation-42

= UN/CEFACT Recommendation 42

image:https://travis-ci.com/metanorma/unece-cefact-recommendation-42.svg?branch=master["Build Status", link="https://travis-ci.com/metanorma/unece-cefact-recommendation-42"]
image:https://ci.appveyor.com/api/projects/status/350pbtyt6g3pk88s?svg=true["AppVeyor Build Status", link="https://ci.appveyor.com/project/ribose/unece-cefact-recommendation-42"]

This document is available in its rendered forms here:

* https://metanorma.github.io/unece-cefact-recommendation-42/[UN/CEFACT Recommendation 42 (HTML)]
* https://metanorma.github.io/unece-cefact-recommendation-42/unece-cefact-recommendation-42.pdf[PDF]
* https://metanorma.github.io/unece-cefact-recommendation-42/unece-cefact-recommendation-42.xml[Metanorma XML]
* https://metanorma.github.io/unece-cefact-recommendation-42/unece-cefact-recommendation-42.rxl[Relaton XML (Bibliographic item)]


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/unece-cefact-recommendation-42/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute. For Windows OS please use `Makefile.win`


== Building The Document

[source,sh]
----
make clean all
----

or 

[source,sh]
----
make -f Makefile.win clean all
----

for Windows OS (Also to avoid of docker sharing issues please checkout sources to your %USERPROFILE% directory)

The following outputs will be built:

* UNECE XML (https://github.com/metanorma/metanorma-model-unece) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open unece-*.html
----

